name: CI (Ubuntu Qt)

on:
  push:
  pull_request:

jobs:
  build-ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake ninja-build pkg-config \
            libglm-dev libgl1-mesa-dev mesa-common-dev \
            qt6-base-dev qt6-base-dev-tools
      - name: Configure (Release)
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DENABLE_GUI=ON
      - name: Build
        run: cmake --build build -j
      - name: Smoke test console
        run: ./build/RadiationSimConsole --version || true
